set vTableName 		= 'DIM_FATOR';
set vFileNameOrigin = 'DIM_FATOR.QVD';
set vFileNameOutput = 'DIM_FATOR.QVD';

$(vTableName):
LOAD
    AutoNumber(codigo_ocorrencia3) as %KeyFator,
    fator_nome,
    fator_aspecto,
    fator_condicionante,
    fator_area
FROM [$(vPathExtract)$(vFileNameOrigin)](QVD);


STORE $(vTableName) INTO [$(vPathTransform)$(vFileNameOutput)](qvd);

DROP TABLE $(vTableName);
